package com.kaizzinho.cobbletunes.client.sound

enum class MusicContext {
    AMBIENCE,
    WILD_BATTLE,
    TRAINER_BATTLE,
    GYM_LEADER_BATTLE,
    ELITE_FOUR_BATTLE,
    CHAMPION_BATTLE,
    PVP_BATTLE,
    FACTION_BATTLE,
    FRONTIER_BRAIN_BATTLE,
    BATTLE_TOWER_BATTLE,
    LEGENDARY_BATTLE,
    VICTORY,
    GYM_AMBIENCE,
    POKECENTER,
    POKEMART,
    BATTLE_TOWER,
    SPECIAL_STRUCTURE,
    MENU,
    VANILLA_STRUCTURE
}
